version: "3.9"

services:
  backend:
    container_name: mlmv-backend-prod
    build:
      context: .
      target: prod
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  db:
    container_name: mlmv-db-prod
    image: postgres:13
    restart: always
    env_file:
      - .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend_network

  redis:
    container_name: mlmv-redis-prod
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data/
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  db-data:
  redis-data:
