version: "3.9"
services:
  backend:
    container_name: mlmv-backend-dev
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level debug
    build:
      context: .
      target: prod
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    networks:
      - backend_network
  db:
    container_name: mlmv-db-dev
    image: "postgres:13"
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    networks:
      - backend_network
  redis:
    container_name: mlmv-redis-dev
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend_network
networks:
  backend_network:
    driver: bridge
