"""Updated text field

Revision ID: 1d2b54831f1e
Revises: 3fdb2e280d38
Create Date: 2023-04-11 23:09:51.185422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2b54831f1e'
down_revision = '3fdb2e280d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
