"""Changed ini file

Revision ID: 41262bc15d7f
Revises: c44b2d21acb5
Create Date: 2023-04-04 23:07:50.781079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41262bc15d7f'
down_revision = 'c44b2d21acb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
