"""Table creation

Revision ID: c44b2d21acb5
Revises: 
Create Date: 2023-04-04 04:07:03.352536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44b2d21acb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=20000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    schema='public'
    )
    op.create_index(op.f('ix_public_prompts_id'), 'prompts', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_prompts_text'), 'prompts', ['text'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_prompts_text'), table_name='prompts', schema='public')
    op.drop_index(op.f('ix_public_prompts_id'), table_name='prompts', schema='public')
    op.drop_table('prompts', schema='public')
    # ### end Alembic commands ###
